### ISSUE TITLE
video transcription pipeline

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-video-pipeline#1]
As an data analyst, I want to have a clean transcript of video recordings automatically generated when a discussion completes. One way to do this would be to use openai's [Whisper](https://openai.com/research/whisper) model to make a time-aligned transcription of the individual audio tracks. (The lab has an openai account to make this easier, or an open-source version that can be run locally). 

## tasks
- [ ] learn how to use the whisper API to transcribe an audio file and get time-stamped voice-to-text. Test with some local files
- [ ] output data using a format consistent with recommendations from: https://www.mikeyeomans.info/papers/PGCR_yeomans.pdf, possibly as a standard `.vtt` or `.srt` file for each participant.
- [ ] combine these into a turn-level CSV including all participants, ordered by the speaker start time...
- [ ] Learn how to hook this up to our S3, possibly needing to generate pre-signed URLs to pass to the whisper API, or maybe they have a direct AWS connection.
- [ ] Save both the "captions" files and the aggregate turn-level csv in the video bucket.

Ideally, we could set this up to run automatically whenever a new video becomes available on the S3 bucket, but for now we can run it manually on particular videos. Not sure if we need to set it up as an AWS lambda, or some other format.

## Practice videos
A description of the recording format is here: https://github.com/Watts-Lab/deliberation-empirica/issues/384#issuecomment-1405278431

We have a bucket with some videos for practicing on here: https://wattslab-video-test-public.s3.amazonaws.com/, some example files:
- https://wattslab-video-test-public.s3.amazonaws.com/01GR9ED3G57XJBBA77068BNH90/1675354384929-1e60214d-05d1-401e-9bd9-d117f5bec0f0-cam-audio-1675354390747
- https://wattslab-video-test-public.s3.amazonaws.com/01GR9ED3G57XJBBA77068BNH90/1675354384929-1e60214d-05d1-401e-9bd9-d117f5bec0f0-cam-video-1675354390750

**Comment by JamesPHoughton** [comment]
Plan is for @mxumary to explore how to do this and decide if its a task she wants to take on, and form a full plan by end of september.

**Comment by mxumary** [comment]
Todo: make a document (Google doc) that shows a table of all of the possible API options -- talk about pricing, free trials, criticisms from online
Overall, it seems like Whisper (or stable-ts?) is the best option so far
